import ClientProvider from "../components/ClientProvider";
import Login from "../components/Login";
import { SessionProvider } from "../components/SessionProvider";
import SideBar from "../components/SideBar";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import "../styles/globals.css";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "ronengpt",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              <div
                className="bg-[#178b6e] max-w-xs h-screen overflow-y-auto
          md:min-w-[20rem]"
              >
                <SideBar />
              </div>

              <ClientProvider />

              <div className="bg-[#11A37F] flex-1">{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
